### PR TITLE
Update autoconf, automake, cmake, meson and ninja

### PR DESCRIPTION
**Pull request by Nomis101**
Interestingly, autoconf has been updated after around 8 years. 😀

### CODE REVIEW

**Comment by Nomis101** [comment]
Forgotten to mention, that for sure I've tested, that HandBrake builds nicely with this on macOS.

**Comment by bradleysepos** [comment]
Thought I commented on this but apparently I just left the tab open. 🤷‍♂️ Hoping to get to it this weekend. The autoconf thing surprised me, too, when I saw it.

**Comment by bradleysepos** [comment]
Gonna punt on this for a bit as I can't build automake. Seems we need this or a similar fix to be released: https://git.savannah.gnu.org/cgit/automake.git/commit/?id=ccb57553e3433df3e52e534e6f87915db23ff9a5

**Comment by Nomis101** [comment]
Interesting, automake did build just fine for me. I deleted automake just now and it did build again nicely.

**Comment by Nomis101** [comment]
Did you find out, why you couldn't build automake? For me all of the contribs build fine.

**Comment by galad87** [comment]
Superseded by 4d38ed390af3f739e61c0322b65cbca0b282984f

**Pull request closed without merging**
